services:
  api:
    image: node:21.6.2
    container_name: "api"
    depends_on: 
      redis:
        condition: service_healthy

  redis:
    image: redis:7.2
    container_name: "redis"
    healthcheck:
      test: ["CMD", "redis-cli"]
      interval: 5s
      timeout: 5s
      retries: 4
    

