services:
  api:
    image: "python-node"
    container_name: "api"
    working_dir: "/usr/app"
    volumes: 
      - "$PWD:/usr/app"
    command: ["nodemon", "app.js"]
    ports: 
      - 8080:8000
    depends_on: 
      redis:
        condition: service_healthy

  redis:
    image: redis:7.2
    container_name: "redis"
    healthcheck:
      test: ["CMD", "redis-cli"]
      interval: 5s
      timeout: 5s
      retries: 4
    

